development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: maintainapp_development
  pool: 5
  host: localhost
  username: root
  password: 123456
  #socket: /tmp/mysql.sock
  #**socket: /opt/local/var/run/mysql5/mysqld.sock**
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: maintainapp_test
  pool: 5
  username: root
  password: 123456
  #socket: /tmp/mysql.sock
  #socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: maintainapp_production
  pool: 5
  username: root
  password: 123456
  #socket: /tmp/mysql.sock
  #socket: **/opt/local/var/run/mysql5/mysqld.sock**